[build]
  base = "master"
  command = ""
  publish = "src"

# Site Redirects

[[redirects]]
  from = "/gb/*"
  to = "https://gb.thebsides.co.uk/:splat"
  status = 200

[[redirects]]
  from = "/de/*"
  to = "https://de.thebsides.co.uk/:splat"
  status = 200

[[redirects]]
  from = "/ie/*"
  to = "https://ie.thebsides.co.uk/:splat"
  status = 200

# Location redirects

# Must use ISO 3166 country codes for country values
# https://dev.maxmind.com/geoip/legacy/codes/iso3166/

# Can also do Lang/Country pairs
# {Language = ["en"], Country = ["GB"]}

[[redirects]]
  from = "/js/*"
  to = "/js/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/gb/"
  status = 302
  force = true
  conditions = {Country = ["gb"]}

[[redirects]]
  from = "/*"
  to = "/de/"
  status = 302
  force = true
  conditions = {Country = ["de"]}

[[redirects]]
  from = "/*"
  to = "/ie/"
  status = 302
  force = true
  conditions = {Country = ["ie"]}
